### ISSUE TITLE
dataset config not provide

### ISSUE THREAD

**Issue by JustinRochester** [zyszxhy/FoRA#1]
Thank you for your exciting work.

I would like to ask, where can I find the dataset config file **drone_vehicle_m.yaml**? I haven't been able to find it.

**Comment by zyszxhy** [comment]
I uploaded the yaml file of the dataset in the FoRA/ultralytics/cfg/datasets folder. The DroneVehicle data set related files can be downloaded [here](https://drive.google.com/drive/folders/1v91V7bcr6Hu6gRzDJ1zK7_YKOJdaxaBA?usp=drive_link). Hope it helps you.

**Comment by Warriors-go** [comment]
> I uploaded the yaml file of the dataset in the FoRA/ultralytics/cfg/datasets folder. The DroneVehicle data set related files can be downloaded [here](https://drive.google.com/drive/folders/1v91V7bcr6Hu6gRzDJ1zK7_YKOJdaxaBA?usp=drive_link). Hope it helps you.

Thanks for your great work! The address of the files related to the DroneVehicle dataset you provided is invalid. Could you upload them again? Thank you!

**Comment by zyszxhy** [comment]
I'm sorry I didn't notice the permission issue when uploading the data. I have modified the permission of Google Drive to make it visible to everyone.
